require_relative "../packages-groonga-org-package-task"

class MecabPackageTask < PackagesGroongaOrgPackageTask
  def initialize
    super("mecab", "0.996", nil)
  end

  private
  def define_archive_task
    dist = detect_srpm_dist
    release = "9"
    srpm_name = "#{@rpm_package}-#{@version}-#{@rpm_release}#{dist}.#{release}.src.rpm"

    file srpm_name do
      base_url = detect_srpm_base_url
      download("#{base_url}/#{srpm_name}", srpm_name)
    end

    [@archive_name, yum_spec_in_path].each do |source_file|
      file source_file => srpm_name do
        sh("rpm2cpio #{srpm_name} | cpio -id")
        mv("#{@rpm_package}.spec", yum_spec_in_path)
      end
    end
  end

  def enable_apt?
    false
  end

  def yum_targets_default
    [
      "almalinux-8",
      "centos-8"
    ]
  end

  def detect_srpm_base_url
    base_url = ""
    yum_targets.each do |target|
      if target == "almalinux-8"
        base_url = "https://repo.almalinux.org/almalinux/8.4/AppStream/Source/Packages"
      else
        base_url = "https://vault.centos.org/8.5.2111/AppStream/Source/SPackages"
      end
    end
    base_url
  end

  def detect_srpm_dist
    dist = ""
    yum_targets.each do |target|
      if target == "almalinux-8"
        dist = ".module_el8.4.0+2532+b8928c02"
      else
        dist = ".module_el8.4.0+589+11e12751"
      end
    end
    dist
  end
end

task = MecabPackageTask.new
task.define
