require_relative "../packages-groonga-org-package-task"

class MecabPackageTask < PackagesGroongaOrgPackageTask
  def initialize
    super("mecab", "0.996", nil)
    version = "0.996"
    release = "1"
    base_url = "http://vault.centos.org/8.2.2004/AppStream/Source/SPackages"

    @srpm_base_name = "mecab-#{@version}"
    @dist = ".module_el8.2.0+493+63b41e36.9"

    @srpm_name = "#{@srpm_base_name}-#{release}#{@dist}.src.rpm"
    @download_url = "#{base_url}/#{@srpm_name}"
  end

  private
  def define_archive_task
    dist = ".module_el8.2.0+493+63b41e36.9"
    srpm_name = "#{@rpm_package}-#{@version}-#{@rpm_release}#{dist}.src.rpm"

    file srpm_name do
      base_url = "http://vault.centos.org/8.2.2004/AppStream/Source/SPackages"
      download("#{base_url}/#{srpm_name}", srpm_name)
    end

    [@archive_name, yum_spec_in_path].each do |source_file|
      file source_file => srpm_name do
        sh("rpm2cpio #{srpm_name} | cpio -id")
        mv("#{@rpm_package}.spec", yum_spec_in_path)
      end
    end
  end

  def enable_apt?
    false
  end

  def yum_targets_default
    [
      "centos-8",
    ]
  end
end

task = MecabPackageTask.new
task.define
