require_relative "../packages-groonga-org-package-task"

class FastTextPackageTask < PackagesGroongaOrgPackageTask
  def initialize
    super("fasttext", "0.9.1", nil)
    @original_archive_base_name = "fastText-#{@version}"
    @original_archive_name = "#{@original_archive_base_name}.tar.gz"
  end

  private
  def define_archive_task
    file @original_archive_name do
      base_url = "https://github.com/facebookresearch/fastText/archive/"
      download_url = "#{base_url}/v#{@version}/#{@original_archive_name}"
      download(download_url, @original_archive_name)
    end
    file @archive_name => @original_archive_name do
      sh("tar", "xf", @original_archive_name)
      sh("mv",
         @original_archive_base_name,
         @archive_base_name)
      sh("tar", "czf", @archive_name, @archive_base_name)
      rm_r(@archive_base_name)
    end
  end

  def apt_targets_default
    [
      "debian-buster",
    ]
  end

  def yum_targets_default
    [
      "centos-7",
    ]
  end
end

task = FastTextPackageTask.new
task.define
