# -*- ruby -*-

require_relative "../packages-groonga-org-package-task"

class GroongaArchiveKeyringPackageTask < PackagesGroongaOrgPackageTask
  def initialize
    super("groonga-archive-keyring",
          repository_version,
          latest_commit_time(File.join(__dir__, "..")))
  end

  private
  def define_archive_task
    file @archive_name do
      rm_rf(@archive_base_name)
      mkdir(@archive_base_name)
      sh("tar", "czf", @archive_name, @archive_base_name)
      rm_rf(@archive_base_name)
    end
  end

  def apt_targets_default
    [
      "debian-stretch",
      "debian-buster",
    ]
  end

  def enable_ubuntu?
    false
  end

  def enable_yum?
    false
  end
end

task = GroongaArchiveKeyringPackageTask.new
task.define
