# -*- ruby -*-

require_relative "../packages-groonga-org-package-task"

class GroongaReleasePackageTask < PackagesGroongaOrgPackageTask
  def initialize
    super("groonga-release",
          repository_version,
          detect_release_time)
  end

  def define
    super
    define_yum_latest_task
  end

  private
  def shorten_gpg_key_id(id)
    id[-8..-1]
  end

  def rpm_gpg_key_path(id)
    "RPM-GPG-KEY-#{shorten_gpg_key_id(id).downcase}"
  end

  def generate_gpg_keys
    repository_gpg_key_ids.each do |gpg_key_id|
      path = "#{@archive_base_name}/#{rpm_gpg_key_path(gpg_key_id)}"
      unless system("gpg", "--list-keys", gpg_key_id, :out => IO::NULL)
        sh("gpg",
           "--keyserver", "keyserver.ubuntu.com",
           "--recv-key", gpg_key_id)
      end
      sh("gpg", "--armor", "--export", gpg_key_id, :out => path)
    end
  end

  def generate_repo_files
    targets = [
      {
        id: "almalinux",
        label: "AlmaLinux $releasever",
        distribution: "almalinux",
        version: "$releasever",
        enabled: "1",
      },
      {
        id: "amazon-linux",
        label: "Amazon Linux 2023",
        distribution: "amazon-linux",
        version: "2023",
        enabled: "0",
      },
    ]
    targets.each do |target|
      repo_path = "#{@archive_base_name}/#{repository_name}-#{target[:id]}.repo"
      File.open(repo_path, "w") do |repo|
        repo.puts(<<-REPOSITORY)
[#{repository_name}-#{target[:id]}]
name=#{repository_label} for #{target[:label]} - $basearch
baseurl=#{repository_url}/#{target[:distribution]}/#{target[:version]}/$basearch/
gpgcheck=1
enabled=#{target[:enabled]}
        REPOSITORY
        prefix = "gpgkey="
        repository_gpg_key_ids.each do |gpg_key_id|
          repo.puts(<<-REPOSITORY)
#{prefix}file:///etc/pki/rpm-gpg/#{rpm_gpg_key_path(gpg_key_id)}
          REPOSITORY
          prefix = "       "
        end
      end
    end
  end

  def define_archive_task
    file @archive_name do
      rm_rf(@archive_base_name)
      mkdir(@archive_base_name)
      generate_gpg_keys
      generate_repo_files
      sh("tar", "czf", @archive_name, @archive_base_name)
      rm_rf(@archive_base_name)
    end
  end

  def enable_apt?
    false
  end

  def yum_targets_default
    [
      "almalinux-8",
      "almalinux-9",
      "amazon-linux-2023",
    ]
  end

  def define_yum_latest_task
    namespace :yum do
      yum_targets.each do |target|
        components = target.split("-")
        distribution = components[0..-2].join("-")
        version = components.last
        rpm = [
          yum_dir,
          "repositories",
          distribution,
          version,
          "x86_64",
          "Packages",
          "#{@package}-#{@rpm_version}-#{@rpm_release}.noarch.rpm",
        ].join("/")

        aarch64_rpm = [
          yum_dir,
          "repositories",
          distribution,
          version,
          "aarch64",
          "Packages",
          "#{@package}-#{@rpm_version}-#{@rpm_release}.noarch.rpm",
        ].join("/")
        aarch64_dir = File.dirname(aarch64_rpm)
        directory aarch64_dir
        file aarch64_rpm => [rpm, aarch64_dir] do
          cp(rpm, aarch64_rpm)
        end
        task :aarch64 => aarch64_rpm

        latest_rpm = [
          yum_dir,
          "repositories",
          distribution,
          version,
          "#{@package}-latest.noarch.rpm",
        ].join("/")
        file latest_rpm => rpm do
          cp(rpm, latest_rpm)
        end
        task :latest => latest_rpm
      end
      task :release => :aarch64
      task :release => :latest
    end
  end

  def github_repository
    "groonga/packages.groonga.org"
  end
end

task = GroongaReleasePackageTask.new
task.define
