# -*- ruby -*-

require_relative "../packages-groonga-org-package-task"

class ApacheArrowReleasePackageTask < PackagesGroongaOrgPackageTask
  def initialize
    super("apache-arrow-release",
          Helper::APACHE_ARROW_VERSION,
          nil)
  end

  private
  def define_archive_task
    file @archive_name do
      touch(@archive_name)
    end
  end

  def enable_apt?
    false
  end

  def enable_ubuntu?
    false
  end

  def yum_targets_default
    [
      "centos-6",
      "centos-7",
      "centos-8",
    ]
  end

  def yum_build
    yum_targets.each do |target|
      _, version = target.split("-", 2)
      path = "centos/#{version}/x86_64/Packages/"
      path << "#{@package}-#{@version}-#{@rpm_release}.el#{version}.noarch.rpm"
      download("https://apache.bintray.com/arrow/#{path}",
               "#{yum_dir}/repositories/#{path}")
    end
  end
end

task = ApacheArrowReleasePackageTask.new
task.define
