# -*- ruby -*-

require_relative "../packages-groonga-org-package-task"

class ApacheArrowArchiveKeyringPackageTask < PackagesGroongaOrgPackageTask
  def initialize
    super("apache-arrow-archive-keyring",
          Helper::APACHE_ARROW_VERSION,
          nil)
  end

  private
  def define_archive_task
    file @archive_name do
      touch(@archive_name)
    end
  end

  def apt_targets_default
    [
      "debian-stretch",
      "debian-buster",
    ]
  end

  def apt_build
    apt_targets.each do |target|
      _, code_name = target.split("-", 2)
      path = "debian/pool/#{code_name}/main/"
      path << "#{@package[0]}/"
      path << "#{@package}/"
      path << "#{@package}_#{@version}-#{@deb_release}_all.deb"
      download("https://apache.bintray.com/arrow/#{path}",
               "#{apt_dir}/repositories/#{path}")
    end
  end

  def enable_ubuntu?
    false
  end

  def enable_yum?
    false
  end
end

task = ApacheArrowArchiveKeyringPackageTask.new
task.define
